[package]
name = "oan-semantic-recommender"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
oan-core = { path = "../oan-core" }
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
