[package]
name = "oan-did-oan"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
description = "did:oan parsing, generation, and validation utilities."
readme = "README.md"
keywords = ["oan", "did", "identity"]
categories = ["cryptography", "encoding", "parser-implementations"]

[dependencies]
bs58.workspace = true
rand.workspace = true
regex.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
