[package]
name = "oan-credentials"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
description = "Credential models and helpers for OAN."
readme = "README.md"
keywords = ["oan", "credentials", "vc"]
categories = ["authentication", "data-structures"]

[dependencies]
bs58.workspace = true
chrono.workspace = true
ed25519-dalek.workspace = true
oan-core = { path = "../oan-core", version = "1.0.0" }
oan-crypto = { path = "../oan-crypto", version = "1.0.0" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

