[package]
name = "oan-crypto"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
description = "Multi-suite cryptographic helpers for OpenAgenet."
readme = "README.md"
keywords = ["oan", "crypto", "sm2", "sm3", "ed25519"]
categories = ["cryptography"]

[dependencies]
base64.workspace = true
bs58.workspace = true
chrono.workspace = true
ed25519-dalek.workspace = true
futures.workspace = true
hex.workspace = true
oan-core = { path = "../oan-core", version = "1.0.0" }
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sm2.workspace = true
sm3.workspace = true
iref = "3.2"
json-syntax = "0.12"
ssi-claims = "0.7"
ssi-claims-core = "0.2"
ssi-contexts = "0.1"
ssi-data-integrity = { version = "0.4.0", features = ["w3c", "ed25519"] }
ssi-dids = "0.5"
ssi-jwk = "0.4"
ssi-json-ld = "0.3"
ssi-verification-methods = "0.3"
static-iref = "3"
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
